'use-client'
import React from 'react'

function Map({direccion}) {
    const replacements = [
    {from:' '	,to:'%20'},
    {from:'!'	,to:'%21'},
    {from:'#'	,to:'%23'},
    {from:'$'	,to:'%24'},
    {from:'%'	,to:'%25'},
    {from:'&'	,to:'%26'},
    {from:"'"	,to:'%27'},
    {from:'('	,to:'%28'},
    {from:')'	,to:'%29'},
    {from:'*'	,to:'%2A'},
    {from:'+'	,to:'%2B'},
    {from:','	,to:'%2C'},
    {from:'-'	,to:'%2D'},
    {from:'.'	,to:'%2E'},
    {from:'/'	,to:'%2F'},
    {from:':'	,to:'%3A'},
    {from:';'	,to:'%3B'},
    {from:'<'	,to:'%3C'},
    {from:'='	,to:'%3D'},
    {from:'>'	,to:'%3E'},
    {from:'?'	,to:'%3F'},
    {from:'@'	,to:'%40'},
    {from:'['	,to:'%5B'},
    {from:'\\'	,to:'%5C'},
    {from:']'	,to:'%5D'},
    {from:'^'	,to:'%5E'},
    {from:'_'	,to:'%5F'},
    {from:'`'	,to:'%60'},
    {from:'{'	,to:'%7B'},
    {from:'|'	,to:'%7C'},
    {from:'}'	,to:'%7D'},
    {from:'~'	,to:'%7E'},
    {from:' '	,to:'%7F'},
    {from:'€'	,to:'%E2%82%AC'},
    {from:'‚'	,to:'%E2%80%9A'},
    {from:'ƒ'	,to:'%C6%92'},
    {from:'„'	,to:'%E2%80%9E'},
    {from:'…'	,to:'%E2%80%A6'},
    {from:'†'	,to:'%E2%80%A0'},
    {from:'‡'	,to:'%E2%80%A1'},
    {from:'ˆ'	,to:'%CB%86'},
    {from:'‰'	,to:'%E2%80%B0'},
    {from:'Š'	,to:'%C5%A0'},
    {from:'‹'	,to:'%E2%80%B9'},
    {from:'Œ'	,to:'%C5%92'},
    {from:'Ž'	,to:'%C5%BD'},
    {from:'‘'	,to:'%E2%80%98'},
    {from:'’'	,to:'%E2%80%99'},
    {from:'“'	,to:'%E2%80%9C'},
    {from:'”'	,to:'%E2%80%9D'},
    {from:'•'	,to:'%E2%80%A2'},
    {from:'–'	,to:'%E2%80%93'},
    {from:'—'	,to:'%E2%80%94'},
    {from:''	  ,to:'%CB%9C'},
    {from:'™'	,to:'%E2%84'},
    {from:'š'	,to:'%C5%A1'},
    {from:'›'	,to:'%E2%80'},
    {from:'œ'	,to:'%C5%93'},
    {from:'ž'	,to:'%C5%BE'},
    {from:'Ÿ'	,to:'%C5%B8'},
    {from:' '	,to:'%C2%A0'},
    {from:'¡'	,to:'%C2%A1'},
    {from:'¢'	,to:'%C2%A2'},
    {from:'£'	,to:'%C2%A3'},
    {from:'¤'	,to:'%C2%A4'},
    {from:'¥'	,to:'%C2%A5'},
    {from:'¦'	,to:'%C2%A6'},
    {from:'§'	,to:'%C2%A7'},
    {from:'¨'	,to:'%C2%A8'},
    {from:'©'	,to:'%C2%A9'},
    {from:'ª'	,to:'%C2%AA'},
    {from:'«'	,to:'%C2%AB'},
    {from:'¬'	,to:'%C2%AC'},
    {from:'­'	,to:'%C2%AD'},
    {from:'®'	,to:'%C2%AE'},
    {from:'¯'	,to:'%C2%AF'},
    {from:'°'	,to:'%C2%B0'},
    {from:'±'	,to:'%C2%B1'},
    {from:'²'	,to:'%C2%B2'},
    {from:'³'	,to:'%C2%B3'},
    {from:'´'	,to:'%C2%B4'},
    {from:'µ'	,to:'%C2%B5'},
    {from:'¶'	,to:'%C2%B6'},
    {from:'·'	,to:'%C2%B7'},
    {from:'¸'	,to:'%C2%B8'},
    {from:'¹'	,to:'%C2%B9'},
    {from:'º'	,to:'%C2%BA'},
    {from:'»'	,to:'%C2%BB'},
    {from:'¼'	,to:'%C2%BC'},
    {from:'½'	,to:'%C2%BD'},
    {from:'¾'	,to:'%C2%BE'},
    {from:'¿'	,to:'%C2%BF'},
    {from:'À'	,to:'%C3%80'},
    {from:'Á'	,to:'%C3%81'},
    {from:'Â'	,to:'%C3%82'},
    {from:'Ã'	,to:'%C3%83'},
    {from:'Ä'	,to:'%C3%84'},
    {from:'Å'	,to:'%C3%85'},
    {from:'Æ'	,to:'%C3%86'},
    {from:'Ç'	,to:'%C3%87'},
    {from:'È'	,to:'%C3%88'},
    {from:'É'	,to:'%C3%89'},
    {from:'Ê'	,to:'%C3%8A'},
    {from:'Ë'	,to:'%C3%8B'},
    {from:'Ì'	,to:'%C3%8C'},
    {from:'Í'	,to:'%C3%8D'},
    {from:'Î'	,to:'%C3%8E'},
    {from:'Ï'	,to:'%C3%8F'},
    {from:'Ð'	,to:'%C3%90'},
    {from:'Ñ'	,to:'%C3%91'},
    {from:'Ò'	,to:'%C3%92'},
    {from:'Ó'	,to:'%C3%93'},
    {from:'Ô'	,to:'%C3%94'},
    {from:'Õ'	,to:'%C3%95'},
    {from:'Ö'	,to:'%C3%96'},
    {from:'×'	,to:'%C3%97'},
    {from:'Ø'	,to:'%C3%98'},
    {from:'Ù'	,to:'%C3%99'},
    {from:'Ú'	,to:'%C3%9A'},
    {from:'Û'	,to:'%C3%9B'},
    {from:'Ü'	,to:'%C3%9C'},
    {from:'Ý'	,to:'%C3%9D'},
    {from:'Þ'	,to:'%C3%9E'},
    {from:'ß'	,to:'%C3%9F'},
    {from:'à'	,to:'%C3%A0'},
    {from:'á'	,to:'%C3%A1'},
    {from:'â'	,to:'%C3%A2'},
    {from:'ã'	,to:'%C3%A3'},
    {from:'ä'	,to:'%C3%A4'},
    {from:'å'	,to:'%C3%A5'},
    {from:'æ'	,to:'%C3%A6'},
    {from:'ç'	,to:'%C3%A7'},
    {from:'è'	,to:'%C3%A8'},
    {from:'é'	,to:'%C3%A9'},
    {from:'ê'	,to:'%C3%AA'},
    {from:'ë'	,to:'%C3%AB'},
    {from:'ì'	,to:'%C3%AC'},
    {from:'í'	,to:'%C3%AD'},
    {from:'î'	,to:'%C3%AE'},
    {from:'ï'	,to:'%C3%AF'},
    {from:'ð'	,to:'%C3%B0'},
    {from:'ñ'	,to:'%C3%B1'},
    {from:'ò'	,to:'%C3%B2'},
    {from:'ó'	,to:'%C3%B3'},
    {from:'ô'	,to:'%C3%B4'},
    {from:'õ'	,to:'%C3%B5'},
    {from:'ö'	,to:'%C3%B6'},
    {from:'÷'	,to:'%C3%B7'},
    {from:'ø'	,to:'%C3%B8'},
    {from:'ù'	,to:'%C3%B9'},
    {from:'ú'	,to:'%C3%BA'},
    {from:'û'	,to:'%C3%BB'},
    {from:'ü'	,to:'%C3%BC'},
    {from:'ý'	,to:'%C3%BD'},
    {from:'þ'	,to:'%C3%BE'},
    {from:'ÿ'	,to:'%C3%BF'},
    ]

    let dir = (Array.from(direccion)).map(l=>replacements.find(el => el.from === l) ? replacements.find(el => el.from === l).to : l).reduce((acc,el)=>acc.concat(el), '')
    dir = `"https://maps.google.com/maps?width=800&amp;height=450&amp;hl=en&amp;q=${dir}+(Tu%20propiedad%20Tasada)&amp;t=p&amp;z=14&amp;ie=UTF8&amp;iwloc=B&amp;output=embed"`
    console.log(dir);
    
  return (
    <div class='space-from-header'>
               
      <iframe class="map" /* width="800" height="450" */ frameborder="0" scrolling="no" marginheight="0" marginwidth="0" id="gmap_canvas" src="https://maps.google.com/maps?width=800&amp;height=450&amp;hl=en&amp;q=Avenida%20de%20Mayo%20866%2C%20Buenos%20Aires+(Tu%20propiedad%20Tasada)&amp;t=p&amp;z=14&amp;ie=UTF8&amp;iwloc=B&amp;output=embed"></iframe>
      {/* <a href='https://maps-generator.com/'>Maps Generator</a> */}


      
    </div>
  )
}

export default Map

