const ciudades = [
    'Barracas',
    'Parque Patricios',
    'La Boca',
    'Nueva Pompeya',
    'Villa Lugano',
    'Villa Soldati',
    'Recoleta',
    'Coghlan',
    'Villa Urquiza',
    'Saavedra',
    'Villa Puevrredon',
    'Belgrano',
    'Nuñez',
    'Colegiales',
    'Palermo',
    'Almagro',
    'Boedo',
    'Caballito',
    'Flores',
    'Parque Chacabuco',
    'Villa Crespo',
    'Chacarita',
    'Villa Ortuzar',
    'Agronomía',
    'Parque Chas',
    'Paternal',
    'Puerto Madero',
    'Retiro',
    'San Telmo',
    'San Nicolas',
    'Monserrat',
    'Constitucion',
    'San Cristobal',
    'Balvanera',
    'Liniers',
    'Mataderos',
    'Parque Avellaneda',
    'Villa Luro',
    'Monte Castro',
    'Floresta',
    'Versalles',
    'Villa Real',
    'Villa Devoto',
    'Villa del Parque',
    'Villa General Mitre',
    'Villa Santa Rita',
    
  ];

  export default ciudades;